services:
  # HTTP延迟测试主服务
  http-latency-test-node1:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test1
    volumes: []
    working_dir: /app
    environment: []
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP1}
    cap_add:
      - NET_ADMIN
  http-latency-test-node2:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test2
    volumes: []
    working_dir: /app
    environment: []
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP2}
    cap_add:
      - NET_ADMIN
  http-latency-test-node3:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test3
    volumes: []
    working_dir: /app
    environment: []
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP3}
    cap_add:
      - NET_ADMIN

  http-latency-test-node4:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test4
    volumes: []
    working_dir: /app
    environment: []
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP4}
    cap_add:
      - NET_ADMIN

  http-latency-test-node5:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test5
    volumes: []
    working_dir: /app
    environment: []
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP5}
    cap_add:
      - NET_ADMIN

networks:
  lan:
    driver: ipvlan
    driver_opts:
      parent: ${NETWORD_CARD}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: ${LAN_SUBNET}
          gateway: ${LAN_GATEWAY}