services:
  # HTTP延迟测试主服务
  http-latency-test-node1:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test1
    volumes:
      - ./logs/node1:/app/logs
    working_dir: /app
    environment:
      # 指定时区到上海
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP1}
    cap_add:
      - NET_ADMIN
  http-latency-test-node2:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test2
    volumes:
      - ./logs/node2:/app/logs
    working_dir: /app
    environment:
      # 指定时区到上海
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP2}
    cap_add:
      - NET_ADMIN
  http-latency-test-node3:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test3
    volumes:
      - ./logs/node3:/app/logs
    working_dir: /app
    environment:
      # 指定时区到上海
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP3}
    cap_add:
      - NET_ADMIN

  http-latency-test-node4:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test4
    volumes:
      - ./logs/node4:/app/logs
    working_dir: /app
    environment:
      # 指定时区到上海
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP4}
    cap_add:
      - NET_ADMIN

  http-latency-test-node5:
    image: dockerhub.tradingx.pro/tradingx/cgolatencytest:latest
    container_name: gocpptest-http-latency-test5
    volumes:
      - ./logs/node5:/app/logs
    working_dir: /app
    environment:
      # 指定时区到上海
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP5}
    cap_add:
      - NET_ADMIN

networks:
  lan:
    driver: ipvlan
    driver_opts:
      parent: ${NETWORK_CARD}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: ${LAN_SUBNET}
          gateway: ${LAN_GATEWAY}