
services:
  # HTTP延迟测试主服务
  http-latency-test-node1:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP1}
    cap_add:
      - NET_ADMIN
  http-latency-test-node2:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP2}
    cap_add:
      - NET_ADMIN
  http-latency-test-node3:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP3}
    cap_add:
      - NET_ADMIN

  http-latency-test-node4:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP4}
    cap_add:
      - NET_ADMIN

  http-latency-test-node5:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP5}
    cap_add:
      - NET_ADMIN

  http-latency-test-node6:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gocpptest-http-latency-test
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - LD_LIBRARY_PATH=/app/http_test
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: ${LOCALIP6}
    cap_add:
      - NET_ADMIN
      
networks:
  lan:
    driver: ipvlan
    driver_opts:
      parent: enX0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: ${LAN_SUBNET}
          gateway: ${LAN_GATEWAY}

